index:
    path: /
    defaults: { _controller: 'App\Controller\IndexController::indexAction' }

ajax_message:
    path: /ajax_message
    defaults: { _controller: 'App\Controller\IndexController::sendMsgAction' }
    methods:  [POST]


